main:
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 10
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 20
  - identifier: search
    name: Search
    url: /search/
    weight: 30
  - identifier: github
    name: "Github"
    url: https://github.com/kiapanahi
    weight: 40
