baseURL: https://kiapanahi.github.io/
languageCode: en-us
theme: PaperMod
title: The Wannabe Geek
params:
  homeInfoParams:
    Title: Hi there!!
    Content: this is the content of home info...

  profileMode:
    enabled: true
    title: "Kia Panahi Rad"
    subtitle: "Curious dev."
    buttons:
      - name: Archives
        url: "/archives"

  socialIcons:
    - name: "Twitter"
      url: "https://twitter.com/@KiaPanahiRad"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/kiapanahirad/"
    - name: "GitHub"
      url: "https://github.com/kiapanahi"
    - name: "StackOverflow"
      url: "https://stackoverflow.com/users/2243741/kia-panahi-rad"
