env: development
homeInfoParams:
  Title: "Kia's Blog (DEV)"
  Content: |-
    A Solutions Architect with a passion for problem-solving and continuous learning.
    
    I studied Computer Science and now enjoy challenging myself trying to apply my knowledge to design software solutions.

    I -*occasionally*- use this space to share my takes on technology, personal interests, and the occasional exploration of new ideas.
